### ISSUE TITLE
jsaddle-dom-0.9.3.1 breaks build with GHC-8.2

### ISSUE THREAD

**Issue by nomeata** [ghcjs/jsaddle-dom#12]
Sorry for complaining about old compiler versions… but I get
```
[  2 of 599] Compiling JSDOM.Types      ( src/JSDOM/Types.hs, dist/build/JSDOM/Types.js_o )

src/JSDOM/Types.hs:1037:9: error:
    • Variable not in scope: (<>) :: t0 -> String -> t1
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Prelude.Compat),
        ‘*>’ (imported from Prelude.Compat),
        ‘<$’ (imported from Prelude.Compat)
     |
1037 |         <> T.unpack destType <> " requested."
     |         ^^

src/JSDOM/Types.hs:1037:30: error:
    • Variable not in scope: (<>) :: t1 -> [Char] -> IO obj'
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Prelude.Compat),
        ‘*>’ (imported from Prelude.Compat),
        ‘<$’ (imported from Prelude.Compat)
     |
1037 |         <> T.unpack destType <> " requested."
     |                              ^^
cabal: Failed to build jsaddle-dom-0.9.3.1 (which is required by
exe:kaleidogen from kaleidogen-0.1). See the build log above for details.
```
with ghcjs-8.2.

This was broken with #11, which made it work with GHC-8.4, but not GHC-8.2. Maybe you don’t care about GHC-8.2 (fair enough), in that case you could edit the metadata on hackage to tighten the bounds.

**Comment by nomeata** [comment]
Oh, or simply use
```
import Data.Monoid.Compat ((<>))
```
I believe.
